version: "3.9"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.7
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:6.2.7
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  activemq:
    image: webcenter/activemq:latest
    ports:
      - "61616:61616"
      - "8161:8161"
      - "1883:1883"

volumes:
  activemq-data:


